"""Formal checks of the generated RTL with SymbiYosys (W <= 8).

Simulation (``hw_dse.rtl.sim``) proves the generated designs compute the
golden model's outputs for every angle, for *one* input sequence. Formal
verification adds what simulation cannot: properties that hold for *every*
input sequence, including arbitrary gaps and back-to-back requests and every
possible residual state after the pipeline fills. Two kinds of check, kept
small (W = 8) so they prove in seconds:

Equivalence: ``pipelined_m`` == ``pipelined`` (``equiv_*`` jobs)
    Both are instantiated with the same numerics and driven by the same
    free inputs (the solver chooses ``valid_in`` and ``theta_in`` every
    cycle). ``pipelined_m`` has the shorter latency, so its outputs pass
    through ``D = L_pipelined - L_pipelined_m`` delay registers; then
    ``valid_out`` must match every cycle and ``cos_out``/``sin_out`` must
    match whenever it is high. Proved by k-induction (``mode prove``), i.e.
    for unbounded time, not just a bounded trace.

Latency and handshake: every family (``latency_*`` jobs)
    With L the documented latency (:attr:`ArchConfig.latency_cycles`):

    * ``valid_out == $past(valid_in && ready, L)``: every accepted angle
      produces exactly one result, exactly L cycles later, and no result
      appears from nowhere;
    * pipelined families: ``ready`` is always high;
    * FSM families: ``ready`` is low for the L-1 cycles after an accepted
      angle and high again on the L-th, so the initiation interval is L.

    These are also proved by k-induction.

Reset is assumed in the initial state only; after that the solver is free.

The jobs (``.sby`` files plus their wrapper modules) are written by
:func:`write_jobs` into ``formal/`` and committed. The generated DUT RTL they
read is written to ``build/formal/rtl/`` (not committed); ``python -m
hw_dse.rtl.formal`` regenerates both and runs every job, recording the
results in ``eval/data/formal_results.csv``.
"""

from __future__ import annotations

import csv
import re
import shutil
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from hw_dse.families import ArchConfig
from hw_dse.rtl.generator import REPO_ROOT, generate

FORMAL_DIR = REPO_ROOT / "formal"
RTL_DIR = REPO_ROOT / "build" / "formal" / "rtl"
RESULTS_CSV = REPO_ROOT / "eval" / "data" / "formal_results.csv"
SOLVER = "z3"


def _a(family: str, **p: object) -> ArchConfig:
    base: dict[str, object] = {"data_width": 8, "n_iter": 7}
    base.update(p)
    return ArchConfig.from_params(family, base)  # type: ignore[arg-type]


EQUIV_PAIRS: dict[str, ArchConfig] = {
    "equiv_m2_trunc": _a("pipelined_m", n_iter=7, m=2),
    "equiv_m3_round": _a("pipelined_m", n_iter=9, angle_guard=-1, frac_guard=2, rounding="round", m=3),
    "equiv_m4_round": _a("pipelined_m", n_iter=8, angle_guard=2, frac_guard=1, rounding="round", m=4),
}
"""pipelined_m designs checked against ``pipelined`` with the same numerics."""

LATENCY_DUTS: dict[str, ArchConfig] = {
    "latency_iterative": _a("iterative", n_iter=6),
    "latency_unrolled_k": _a("unrolled_k", n_iter=9, frac_guard=2, rounding="round", k=4),
    "latency_pipelined": _a("pipelined", n_iter=7),
    "latency_pipelined_m": _a("pipelined_m", n_iter=7, m=3),
}


def _as_pipelined(a: ArchConfig) -> ArchConfig:
    return ArchConfig(family="pipelined", numerics=a.numerics)


# ---------------------------------------------------------------------------
# Wrapper modules
# ---------------------------------------------------------------------------

_PORTS = """    input  wire       clk,
    input  wire       rst,
    input  wire       valid_in,
    input  wire [{w1}:0] theta_in"""


def equiv_wrapper(job: str, arch: ArchConfig, ref_arch: ArchConfig | None = None) -> str:
    """``ref_arch`` defaults to ``pipelined`` with ``arch``'s numerics (tests pass a mutant)."""
    ref = generate(ref_arch or _as_pipelined(arch))
    dut = generate(arch)
    w = arch.numerics.data_width
    d = ref.latency - dut.latency
    assert d >= 0
    lines = [
        f"// {job}: {dut.module} (latency {dut.latency}) == {ref.module} (latency {ref.latency})",
        "// after delaying the shorter pipeline by "
        f"{d} cycle(s). Generated by hw_dse.rtl.formal; do not edit.",
        f"module {job} (",
        _PORTS.format(w1=w - 1),
        ");",
        "    reg init = 1'b1;",
        "    always @(posedge clk) init <= 1'b0;",
        "    always @(*) if (init) assume (rst);",
        "",
        f"    wire r_ready, r_valid, m_ready, m_valid;",
        f"    wire [{w - 1}:0] r_cos, r_sin, m_cos, m_sin;",
        f"    {ref.module} ref_i (.clk(clk), .rst(rst), .valid_in(valid_in), .ready(r_ready), .theta_in(theta_in),",
        "        .valid_out(r_valid), .cos_out(r_cos), .sin_out(r_sin));",
        f"    {dut.module} dut_i (.clk(clk), .rst(rst), .valid_in(valid_in), .ready(m_ready), .theta_in(theta_in),",
        "        .valid_out(m_valid), .cos_out(m_cos), .sin_out(m_sin));",
        "",
        f"    // align: delay the pipelined_m outputs by {d} cycle(s)",
        f"    reg [{d}:0] dv;",
        f"    reg [{w - 1}:0] dc [0:{d}];",
        f"    reg [{w - 1}:0] ds [0:{d}];",
        "    always @(*) begin dv[0] = m_valid; dc[0] = m_cos; ds[0] = m_sin; end",
        "    integer i;",
        "    always @(posedge clk) begin",
        f"        for (i = 1; i <= {d}; i = i + 1) begin",
        "            dv[i] <= rst ? 1'b0 : dv[i-1];",
        "            dc[i] <= dc[i-1];",
        "            ds[i] <= ds[i-1];",
        "        end",
        "    end",
        "",
        "    always @(*) begin",
        "        if (!init) begin",
        "            assert (r_ready && m_ready);",
        f"            assert (r_valid == dv[{d}]);",
        f"            if (r_valid) assert (r_cos == dc[{d}] && r_sin == ds[{d}]);",
        "        end",
        "    end",
        "endmodule",
        "",
    ]
    return "\n".join(lines)


def latency_wrapper(job: str, arch: ArchConfig, latency: int | None = None) -> str:
    """``latency`` defaults to the documented one (tests pass a wrong one)."""
    dut = generate(arch)
    w = arch.numerics.data_width
    L = latency or dut.latency
    lines = [
        f"// {job}: {dut.module}, documented latency {L}. Generated by hw_dse.rtl.formal; do not edit.",
        f"module {job} (",
        _PORTS.format(w1=w - 1),
        ");",
        "    reg init = 1'b1;",
        "    always @(posedge clk) init <= 1'b0;",
        "    always @(*) if (init) assume (rst);",
        "",
        "    wire ready, valid_out;",
        f"    wire [{w - 1}:0] cos_out, sin_out;",
        f"    {dut.module} dut_i (.clk(clk), .rst(rst), .valid_in(valid_in), .ready(ready), .theta_in(theta_in),",
        "        .valid_out(valid_out), .cos_out(cos_out), .sin_out(sin_out));",
        "",
        "    // acc_hist[j] = an angle was accepted j cycles ago (0 after reset)",
        "    wire accept = valid_in && ready && !rst;",
        f"    reg [{L}:1] acc_hist;",
        "    always @(posedge clk) begin",
        "        if (rst) acc_hist <= '0;",
        f"        else     acc_hist <= {{acc_hist[{L - 1}:1], accept}};" if L > 1 else "        else     acc_hist <= accept;",
        "    end",
        "",
        "    always @(*) begin",
        "        if (!init && !rst) begin",
        f"            // exactly one result per accepted angle, exactly {L} cycles later",
        f"            assert (valid_out == acc_hist[{L}]);",
    ]
    if arch.is_pipelined:
        lines.append("            assert (ready);  // a new angle every cycle")
    else:
        lines.append(f"            // busy for the {L - 1} cycles after an accept, then ready again")
        busy = " || ".join(f"acc_hist[{j}]" for j in range(1, L))
        # Checked from the first cycle after reset: the FSM resets to idle,
        # so ready must be high until the first accept.
        lines.append(f"            assert (ready == !({busy}));")
    lines += ["        end", "    end", "endmodule", ""]
    return "\n".join(lines)


def sby_text(job: str, rtl_modules: list[str], depth: int) -> str:
    files = [f"../build/formal/rtl/{m}.sv" for m in rtl_modules] + [f"{job}.sv"]
    reads = "\n".join(f"read -formal {Path(f).name}" for f in files)
    return (
        f"# {job}: generated by hw_dse.rtl.formal -- run with `sby -f {job}.sby` from formal/\n"
        "# (first `python -m hw_dse.rtl.formal --write` to generate the DUT RTL into build/formal/rtl/)\n"
        "[options]\n"
        "mode prove\n"
        f"depth {depth}\n\n"
        "[engines]\n"
        f"smtbmc {SOLVER}\n\n"
        "[script]\n"
        f"{reads}\n"
        f"prep -top {job}\n\n"
        "[files]\n" + "\n".join(files) + "\n"
    )


@dataclass
class Job:
    name: str
    kind: str  # "equivalence" | "latency"
    arch: ArchConfig
    wrapper: str
    modules: list[str]
    depth: int


def jobs() -> list[Job]:
    out = []
    for name, a in EQUIV_PAIRS.items():
        ref, dut = generate(_as_pipelined(a)), generate(a)
        out.append(Job(name, "equivalence", a, equiv_wrapper(name, a), [ref.module, dut.module], ref.latency + 4))
    for name, a in LATENCY_DUTS.items():
        d = generate(a)
        out.append(Job(name, "latency", a, latency_wrapper(name, a), [d.module], 2 * d.latency + 8))
    return out


def write_jobs(formal_dir: Path = FORMAL_DIR, rtl_dir: Path = RTL_DIR) -> list[Job]:
    """Write wrappers + .sby files (committed) and DUT RTL (build dir)."""
    formal_dir.mkdir(parents=True, exist_ok=True)
    rtl_dir.mkdir(parents=True, exist_ok=True)
    js = jobs()
    for j in js:
        (formal_dir / f"{j.name}.sv").write_text(j.wrapper)
        (formal_dir / f"{j.name}.sby").write_text(sby_text(j.name, j.modules, j.depth))
        arches = [_as_pipelined(j.arch), j.arch] if j.kind == "equivalence" else [j.arch]
        for a in arches:
            generate(a).write(rtl_dir)
    return js


def tool_status() -> tuple[bool, str]:
    missing = [t for t in ("sby", "yosys", "yosys-smtbmc", SOLVER) if shutil.which(t) is None]
    return (not missing, f"{', '.join(missing)} not on PATH" if missing else "")


def versions() -> dict[str, str]:
    def first(cmd: list[str]) -> str:
        try:
            p = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
            return (p.stdout or p.stderr).strip().splitlines()[0]
        except (OSError, IndexError, subprocess.TimeoutExpired):
            return "unknown"

    sby_dir = Path(shutil.which("sby") or "").resolve().parent
    return {"yosys": first(["yosys", "-V"]), "sby": _sby_version(sby_dir), "solver": f"{SOLVER} " + first([SOLVER, "--version"])}


def _sby_version(_: Path) -> str:
    try:
        p = subprocess.run(["sby", "--version"], capture_output=True, text=True, timeout=30)
        return (p.stdout or p.stderr).strip().splitlines()[0] if p.returncode == 0 else "SBY (version flag unsupported)"
    except (OSError, IndexError, subprocess.TimeoutExpired):
        return "unknown"


def run_custom(name: str, wrapper: str, arches: list[ArchConfig], depth: int, directory: Path,
               timeout_s: float = 900.0, mutate: Any = None) -> str:
    """Write and run a one-off job in ``directory`` (used by the mutation tests).

    ``mutate(module_name, text) -> text`` may rewrite a generated DUT first.
    Returns PASS/FAIL/ERROR."""
    rtl = directory / "build" / "formal" / "rtl"
    fdir = directory / "formal"
    rtl.mkdir(parents=True, exist_ok=True)
    fdir.mkdir(parents=True, exist_ok=True)
    mods = []
    for a in arches:
        d = generate(a)
        text = mutate(d.module, d.text) if mutate else d.text
        (rtl / f"{d.module}.sv").write_text(text)
        mods.append(d.module)
    (fdir / f"{name}.sv").write_text(wrapper)
    (fdir / f"{name}.sby").write_text(sby_text(name, mods, depth))
    j = Job(name, "custom", arches[-1], wrapper, mods, depth)
    return str(run_job(j, fdir, timeout_s)["status"])


def run_job(j: Job, formal_dir: Path = FORMAL_DIR, timeout_s: float = 900.0) -> dict[str, object]:
    t0 = time.time()
    p = subprocess.run(["sby", "-f", f"{j.name}.sby"], cwd=formal_dir, capture_output=True, text=True, timeout=timeout_s)
    out = p.stdout + p.stderr
    m = re.findall(r"DONE \((\w+), rc=(\d+)\)", out)
    status = m[-1][0] if m else "ERROR"
    return {"job": j.name, "kind": j.kind, "key": j.arch.key(), "mode": "prove (k-induction)", "depth": j.depth,
            "status": status, "seconds": round(time.time() - t0, 1), "log_tail": "" if status == "PASS" else out[-1500:]}


def main() -> None:  # pragma: no cover - CLI
    import argparse

    ap = argparse.ArgumentParser(description="write and run the SymbiYosys jobs")
    ap.add_argument("--write", action="store_true", help="only (re)write the jobs and DUT RTL")
    args = ap.parse_args()
    js = write_jobs()
    print(f"wrote {len(js)} jobs to {FORMAL_DIR} and DUT RTL to {RTL_DIR}")
    if args.write:
        return
    ok, why = tool_status()
    if not ok:
        raise SystemExit(f"cannot run: {why}")
    v = versions()
    rows = []
    for j in js:
        r = run_job(j)
        r.update({"yosys": v["yosys"], "sby": v["sby"], "solver": v["solver"]})
        print(f"{r['status']:5s} {j.name:22s} depth {j.depth:3d} {r['seconds']:6.1f}s  {j.arch.key()}")
        if r["log_tail"]:
            print(r["log_tail"])
        rows.append(r)
    with open(RESULTS_CSV, "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=["job", "kind", "key", "mode", "depth", "status", "seconds", "yosys", "sby", "solver"])
        w.writeheader()
        for r in rows:
            w.writerow({k: r[k] for k in w.fieldnames})
    print(f"wrote {RESULTS_CSV}")
    if any(r["status"] != "PASS" for r in rows):
        raise SystemExit(1)


if __name__ == "__main__":  # pragma: no cover
    main()
