// Generated by hw_dse.rtl.generator -- do not edit; regenerate instead.
// family pipelined: one pipeline register per micro-rotation
// design key: pipelined:data_width=16,n_iter=14,angle_guard=0,frac_guard=0,rounding=trunc
// latency 16 cycles (valid_in sampled -> valid_out), one result every 1 cycle(s)
// atan LUT (hw_dse.models.cordic_bitexact.atan_lut(N=14, A=16)): [8192, 4836, 2555, 1297, 651, 326, 163, 81, 41, 20, 10, 5, 3, 1]
// gain pre-compensation (init_x(N=14, frac_bits=14)): 9949
`default_nettype none
module cordic_golden_pipelined (
    input  wire                  clk,
    input  wire                  rst,
    input  wire                  valid_in,
    output wire                  ready,
    input  wire signed [15:0]   theta_in,
    output logic                 valid_out,
    output logic signed [15:0]  cos_out,
    output logic signed [15:0]  sin_out
);
    /* verilator lint_off UNUSEDPARAM */  // documentation: the knobs this module was built for
    localparam int W  = 16;   // data width: angle in, sin/cos out (Q1.14)
    localparam int N  = 14;   // micro-rotations
    localparam int A  = 16;   // angle path width (angle_guard +0)
    localparam int G  = 0;   // fractional guard bits on x/y
    localparam int WX = 18;   // x/y register width = W + 2 headroom + G
    localparam int WZ = 18;   // z register width = A + 2 headroom
    localparam bit ROUND = 1'b0;  // trunc
    localparam int LATENCY = 16;
    /* verilator lint_on UNUSEDPARAM */
    localparam logic [WX-1:0] INIT_X = 18'h026dd;  // K_N in Q1.14
    localparam logic [WZ-1:0] PI     = 18'h08000;  // pi in angle units

    assign ready = 1'b1;  // fully pipelined: a new angle every cycle

    // ---- stage 0: register the input with the quadrant pre-rotation ----
    // Angles in (pi/2, pi) or (-pi, -pi/2) are rotated by -/+pi into the
    // CORDIC convergence range; that flips the sign of x0 (y0 is 0).
    wire [1:0] quadrant = theta_in[15:14];
    wire signed [WZ-1:0] z_in = {{2{theta_in[15]}}, theta_in};
    logic signed [WX-1:0] x_s0;
    logic signed [WZ-1:0] z_s0;
    always_ff @(posedge clk) begin
        case (quadrant)
            2'b01:   begin x_s0 <= -INIT_X; z_s0 <= z_in - PI; end  // (pi/2, pi)
            2'b10:   begin x_s0 <= -INIT_X; z_s0 <= z_in + PI; end  // (-pi, -pi/2)
            default: begin x_s0 <=  INIT_X; z_s0 <= z_in;      end
        endcase
    end

    // valid chain: 16 registers (stage 0, 14 rotation stage(s), output)
    logic [15:0] valid_pipe;
    always_ff @(posedge clk) begin
        if (rst) valid_pipe <= '0;
        else     valid_pipe <= {valid_pipe[14:0], valid_in};
    end
    assign valid_out = valid_pipe[15];

    // ---- stage 1: micro-rotation(s) 0..0, then a register ----
    // micro-rotation 0: shift 0, atan(2^-0) = 8192 (angle LSBs)
    wire x_r0_pos = ~z_s0[17];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r0 = x_s0;
    wire signed [WX-1:0] y_r0 = x_r0_pos ? x_s0 : -x_s0;
    wire signed [WZ-1:0] z_r0 = z_s0 + (18'h02000 ^ {18{x_r0_pos}}) + {17'b0, x_r0_pos};
    logic signed [WX-1:0] x_s1, y_s1;
    logic signed [WZ-1:0] z_s1;
    always_ff @(posedge clk) begin
        x_s1 <= x_r0;
        y_s1 <= y_r0;
        z_s1 <= z_r0;
    end

    // ---- stage 2: micro-rotation(s) 1..1, then a register ----
    // micro-rotation 1: shift 1, atan(2^-1) = 4836 (angle LSBs)
    wire x_r1_pos = ~z_s1[17];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r1 = x_s1 + ({{1{y_s1[17]}}, y_s1[17:1]} ^ {18{x_r1_pos}}) + {17'b0, x_r1_pos};
    wire signed [WX-1:0] y_r1 = y_s1 + ({{1{x_s1[17]}}, x_s1[17:1]} ^ {18{~x_r1_pos}}) + {17'b0, ~x_r1_pos};
    wire signed [WZ-1:0] z_r1 = z_s1 + (18'h012e4 ^ {18{x_r1_pos}}) + {17'b0, x_r1_pos};
    logic signed [WX-1:0] x_s2, y_s2;
    logic signed [WZ-1:0] z_s2;
    always_ff @(posedge clk) begin
        x_s2 <= x_r1;
        y_s2 <= y_r1;
        z_s2 <= z_r1;
    end

    // ---- stage 3: micro-rotation(s) 2..2, then a register ----
    // micro-rotation 2: shift 2, atan(2^-2) = 2555 (angle LSBs)
    wire x_r2_pos = ~z_s2[17];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r2 = x_s2 + ({{2{y_s2[17]}}, y_s2[17:2]} ^ {18{x_r2_pos}}) + {17'b0, x_r2_pos};
    wire signed [WX-1:0] y_r2 = y_s2 + ({{2{x_s2[17]}}, x_s2[17:2]} ^ {18{~x_r2_pos}}) + {17'b0, ~x_r2_pos};
    wire signed [WZ-1:0] z_r2 = z_s2 + (18'h009fb ^ {18{x_r2_pos}}) + {17'b0, x_r2_pos};
    logic signed [WX-1:0] x_s3, y_s3;
    logic signed [WZ-1:0] z_s3;
    always_ff @(posedge clk) begin
        x_s3 <= x_r2;
        y_s3 <= y_r2;
        z_s3 <= z_r2;
    end

    // ---- stage 4: micro-rotation(s) 3..3, then a register ----
    // micro-rotation 3: shift 3, atan(2^-3) = 1297 (angle LSBs)
    wire x_r3_pos = ~z_s3[17];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r3 = x_s3 + ({{3{y_s3[17]}}, y_s3[17:3]} ^ {18{x_r3_pos}}) + {17'b0, x_r3_pos};
    wire signed [WX-1:0] y_r3 = y_s3 + ({{3{x_s3[17]}}, x_s3[17:3]} ^ {18{~x_r3_pos}}) + {17'b0, ~x_r3_pos};
    wire signed [WZ-1:0] z_r3 = z_s3 + (18'h00511 ^ {18{x_r3_pos}}) + {17'b0, x_r3_pos};
    logic signed [WX-1:0] x_s4, y_s4;
    logic signed [WZ-1:0] z_s4;
    always_ff @(posedge clk) begin
        x_s4 <= x_r3;
        y_s4 <= y_r3;
        z_s4 <= z_r3;
    end

    // ---- stage 5: micro-rotation(s) 4..4, then a register ----
    // micro-rotation 4: shift 4, atan(2^-4) = 651 (angle LSBs)
    wire x_r4_pos = ~z_s4[17];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r4 = x_s4 + ({{4{y_s4[17]}}, y_s4[17:4]} ^ {18{x_r4_pos}}) + {17'b0, x_r4_pos};
    wire signed [WX-1:0] y_r4 = y_s4 + ({{4{x_s4[17]}}, x_s4[17:4]} ^ {18{~x_r4_pos}}) + {17'b0, ~x_r4_pos};
    wire signed [WZ-1:0] z_r4 = z_s4 + (18'h0028b ^ {18{x_r4_pos}}) + {17'b0, x_r4_pos};
    logic signed [WX-1:0] x_s5, y_s5;
    logic signed [WZ-1:0] z_s5;
    always_ff @(posedge clk) begin
        x_s5 <= x_r4;
        y_s5 <= y_r4;
        z_s5 <= z_r4;
    end

    // ---- stage 6: micro-rotation(s) 5..5, then a register ----
    // micro-rotation 5: shift 5, atan(2^-5) = 326 (angle LSBs)
    wire x_r5_pos = ~z_s5[17];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r5 = x_s5 + ({{5{y_s5[17]}}, y_s5[17:5]} ^ {18{x_r5_pos}}) + {17'b0, x_r5_pos};
    wire signed [WX-1:0] y_r5 = y_s5 + ({{5{x_s5[17]}}, x_s5[17:5]} ^ {18{~x_r5_pos}}) + {17'b0, ~x_r5_pos};
    wire signed [WZ-1:0] z_r5 = z_s5 + (18'h00146 ^ {18{x_r5_pos}}) + {17'b0, x_r5_pos};
    logic signed [WX-1:0] x_s6, y_s6;
    logic signed [WZ-1:0] z_s6;
    always_ff @(posedge clk) begin
        x_s6 <= x_r5;
        y_s6 <= y_r5;
        z_s6 <= z_r5;
    end

    // ---- stage 7: micro-rotation(s) 6..6, then a register ----
    // micro-rotation 6: shift 6, atan(2^-6) = 163 (angle LSBs)
    wire x_r6_pos = ~z_s6[17];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r6 = x_s6 + ({{6{y_s6[17]}}, y_s6[17:6]} ^ {18{x_r6_pos}}) + {17'b0, x_r6_pos};
    wire signed [WX-1:0] y_r6 = y_s6 + ({{6{x_s6[17]}}, x_s6[17:6]} ^ {18{~x_r6_pos}}) + {17'b0, ~x_r6_pos};
    wire signed [WZ-1:0] z_r6 = z_s6 + (18'h000a3 ^ {18{x_r6_pos}}) + {17'b0, x_r6_pos};
    logic signed [WX-1:0] x_s7, y_s7;
    logic signed [WZ-1:0] z_s7;
    always_ff @(posedge clk) begin
        x_s7 <= x_r6;
        y_s7 <= y_r6;
        z_s7 <= z_r6;
    end

    // ---- stage 8: micro-rotation(s) 7..7, then a register ----
    // micro-rotation 7: shift 7, atan(2^-7) = 81 (angle LSBs)
    wire x_r7_pos = ~z_s7[17];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r7 = x_s7 + ({{7{y_s7[17]}}, y_s7[17:7]} ^ {18{x_r7_pos}}) + {17'b0, x_r7_pos};
    wire signed [WX-1:0] y_r7 = y_s7 + ({{7{x_s7[17]}}, x_s7[17:7]} ^ {18{~x_r7_pos}}) + {17'b0, ~x_r7_pos};
    wire signed [WZ-1:0] z_r7 = z_s7 + (18'h00051 ^ {18{x_r7_pos}}) + {17'b0, x_r7_pos};
    logic signed [WX-1:0] x_s8, y_s8;
    logic signed [WZ-1:0] z_s8;
    always_ff @(posedge clk) begin
        x_s8 <= x_r7;
        y_s8 <= y_r7;
        z_s8 <= z_r7;
    end

    // ---- stage 9: micro-rotation(s) 8..8, then a register ----
    // micro-rotation 8: shift 8, atan(2^-8) = 41 (angle LSBs)
    wire x_r8_pos = ~z_s8[17];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r8 = x_s8 + ({{8{y_s8[17]}}, y_s8[17:8]} ^ {18{x_r8_pos}}) + {17'b0, x_r8_pos};
    wire signed [WX-1:0] y_r8 = y_s8 + ({{8{x_s8[17]}}, x_s8[17:8]} ^ {18{~x_r8_pos}}) + {17'b0, ~x_r8_pos};
    wire signed [WZ-1:0] z_r8 = z_s8 + (18'h00029 ^ {18{x_r8_pos}}) + {17'b0, x_r8_pos};
    logic signed [WX-1:0] x_s9, y_s9;
    logic signed [WZ-1:0] z_s9;
    always_ff @(posedge clk) begin
        x_s9 <= x_r8;
        y_s9 <= y_r8;
        z_s9 <= z_r8;
    end

    // ---- stage 10: micro-rotation(s) 9..9, then a register ----
    // micro-rotation 9: shift 9, atan(2^-9) = 20 (angle LSBs)
    wire x_r9_pos = ~z_s9[17];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r9 = x_s9 + ({{9{y_s9[17]}}, y_s9[17:9]} ^ {18{x_r9_pos}}) + {17'b0, x_r9_pos};
    wire signed [WX-1:0] y_r9 = y_s9 + ({{9{x_s9[17]}}, x_s9[17:9]} ^ {18{~x_r9_pos}}) + {17'b0, ~x_r9_pos};
    wire signed [WZ-1:0] z_r9 = z_s9 + (18'h00014 ^ {18{x_r9_pos}}) + {17'b0, x_r9_pos};
    logic signed [WX-1:0] x_s10, y_s10;
    logic signed [WZ-1:0] z_s10;
    always_ff @(posedge clk) begin
        x_s10 <= x_r9;
        y_s10 <= y_r9;
        z_s10 <= z_r9;
    end

    // ---- stage 11: micro-rotation(s) 10..10, then a register ----
    // micro-rotation 10: shift 10, atan(2^-10) = 10 (angle LSBs)
    wire x_r10_pos = ~z_s10[17];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r10 = x_s10 + ({{10{y_s10[17]}}, y_s10[17:10]} ^ {18{x_r10_pos}}) + {17'b0, x_r10_pos};
    wire signed [WX-1:0] y_r10 = y_s10 + ({{10{x_s10[17]}}, x_s10[17:10]} ^ {18{~x_r10_pos}}) + {17'b0, ~x_r10_pos};
    wire signed [WZ-1:0] z_r10 = z_s10 + (18'h0000a ^ {18{x_r10_pos}}) + {17'b0, x_r10_pos};
    logic signed [WX-1:0] x_s11, y_s11;
    logic signed [WZ-1:0] z_s11;
    always_ff @(posedge clk) begin
        x_s11 <= x_r10;
        y_s11 <= y_r10;
        z_s11 <= z_r10;
    end

    // ---- stage 12: micro-rotation(s) 11..11, then a register ----
    // micro-rotation 11: shift 11, atan(2^-11) = 5 (angle LSBs)
    wire x_r11_pos = ~z_s11[17];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r11 = x_s11 + ({{11{y_s11[17]}}, y_s11[17:11]} ^ {18{x_r11_pos}}) + {17'b0, x_r11_pos};
    wire signed [WX-1:0] y_r11 = y_s11 + ({{11{x_s11[17]}}, x_s11[17:11]} ^ {18{~x_r11_pos}}) + {17'b0, ~x_r11_pos};
    wire signed [WZ-1:0] z_r11 = z_s11 + (18'h00005 ^ {18{x_r11_pos}}) + {17'b0, x_r11_pos};
    logic signed [WX-1:0] x_s12, y_s12;
    logic signed [WZ-1:0] z_s12;
    always_ff @(posedge clk) begin
        x_s12 <= x_r11;
        y_s12 <= y_r11;
        z_s12 <= z_r11;
    end

    // ---- stage 13: micro-rotation(s) 12..12, then a register ----
    // micro-rotation 12: shift 12, atan(2^-12) = 3 (angle LSBs)
    wire x_r12_pos = ~z_s12[17];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r12 = x_s12 + ({{12{y_s12[17]}}, y_s12[17:12]} ^ {18{x_r12_pos}}) + {17'b0, x_r12_pos};
    wire signed [WX-1:0] y_r12 = y_s12 + ({{12{x_s12[17]}}, x_s12[17:12]} ^ {18{~x_r12_pos}}) + {17'b0, ~x_r12_pos};
    wire signed [WZ-1:0] z_r12 = z_s12 + (18'h00003 ^ {18{x_r12_pos}}) + {17'b0, x_r12_pos};
    logic signed [WX-1:0] x_s13, y_s13;
    /* verilator lint_off UNUSEDSIGNAL */ logic signed [WZ-1:0] z_s13; /* verilator lint_on UNUSEDSIGNAL */
    always_ff @(posedge clk) begin
        x_s13 <= x_r12;
        y_s13 <= y_r12;
        z_s13 <= z_r12;
    end

    // ---- stage 14: micro-rotation(s) 13..13, then a register ----
    // micro-rotation 13: shift 13, atan(2^-13) = 1 (angle LSBs)
    wire x_r13_pos = ~z_s13[17];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r13 = x_s13 + ({{13{y_s13[17]}}, y_s13[17:13]} ^ {18{x_r13_pos}}) + {17'b0, x_r13_pos};
    wire signed [WX-1:0] y_r13 = y_s13 + ({{13{x_s13[17]}}, x_s13[17:13]} ^ {18{~x_r13_pos}}) + {17'b0, ~x_r13_pos};
    /* verilator lint_off UNUSEDSIGNAL */
    logic signed [WX-1:0] x_s14, y_s14;
    /* verilator lint_on UNUSEDSIGNAL */
    always_ff @(posedge clk) begin
        x_s14 <= x_r13;
        y_s14 <= y_r13;
    end

    // ---- output register: drop the guard bits ----
    always_ff @(posedge clk) begin
        cos_out <= x_s14[15:0];
        sin_out <= y_s14[15:0];
    end
endmodule
`default_nettype wire
