// Generated by hw_dse.rtl.generator -- do not edit; regenerate instead.
// family unrolled_k: 4 chained micro-rotations per cycle (FSM, barrel shifters)
// design key: unrolled_k:data_width=12,n_iter=11,angle_guard=1,frac_guard=2,rounding=round,k=4
// latency 6 cycles (valid_in sampled -> valid_out), one result every 6 cycle(s)
// atan LUT (hw_dse.models.cordic_bitexact.atan_lut(N=11, A=13)): [1024, 605, 319, 162, 81, 41, 20, 10, 5, 3, 1]
// gain pre-compensation (init_x(N=11, frac_bits=12)): 2487
`default_nettype none
module cordic_golden_unrolled_k (
    input  wire                  clk,
    input  wire                  rst,
    input  wire                  valid_in,
    output wire                  ready,
    input  wire signed [11:0]   theta_in,
    output logic                 valid_out,
    output logic signed [11:0]  cos_out,
    output logic signed [11:0]  sin_out
);
    /* verilator lint_off UNUSEDPARAM */  // documentation: the knobs this module was built for
    localparam int W  = 12;   // data width: angle in, sin/cos out (Q1.10)
    localparam int N  = 11;   // micro-rotations
    localparam int A  = 13;   // angle path width (angle_guard +1)
    localparam int G  = 2;   // fractional guard bits on x/y
    localparam int WX = 16;   // x/y register width = W + 2 headroom + G
    localparam int WZ = 15;   // z register width = A + 2 headroom
    localparam bit ROUND = 1'b1;  // round
    localparam int LATENCY = 6;
    /* verilator lint_on UNUSEDPARAM */
    localparam logic [WX-1:0] INIT_X = 16'h09b7;  // K_N in Q1.12
    localparam logic [WZ-1:0] PI     = 15'h1000;  // pi in angle units

    // FSM: IDLE (accept) -> PRE (quadrant pre-rotation) -> ITER x 3 -> OUT
    localparam logic [1:0] S_IDLE = 2'd0, S_PRE = 2'd1, S_ITER = 2'd2, S_OUT = 2'd3;
    logic [1:0] state;
    logic [1:0] quadrant;
    logic [3:0] base;  // shift amount of the first rotation this cycle (steps of 4)
    logic signed [WX-1:0] x, y;
    logic signed [WZ-1:0] z;
    assign ready = (state == S_IDLE);

    // ---- chained micro-rotation 0 of 4: shift amount base+0 ----
    wire [3:0] sh0 = base + 4'd0;
    logic [WZ-1:0] atan0;
    always_comb begin
        case (sh0)
            4'd0: atan0 = 15'h0400;  // atan(2^-0)
            4'd4: atan0 = 15'h0051;  // atan(2^-4)
            4'd8: atan0 = 15'h0005;  // atan(2^-8)
            default: atan0 = '0;
        endcase
    end
    wire pos0 = ~z[14];
    wire signed [WX:0] ysh0_w = $signed({y, 1'b0}) >>> sh0;
    wire signed [WX:0] xsh0_w = $signed({x, 1'b0}) >>> sh0;
    wire [WX-1:0] ysh0 = ysh0_w[16:1];
    wire [WX-1:0] xsh0 = xsh0_w[16:1];
    wire signed [WX-1:0] x_c0 = x + (ysh0 ^ {16{pos0}}) + {15'b0, (pos0 ^ ysh0_w[0])};
    wire signed [WX-1:0] y_c0 = y + (xsh0 ^ {16{~pos0}}) + {15'b0, (~pos0 ^ xsh0_w[0])};
    wire signed [WZ-1:0] z_c0 = z + (atan0 ^ {15{pos0}}) + {14'b0, pos0};

    // ---- chained micro-rotation 1 of 4: shift amount base+1 ----
    wire [3:0] sh1 = base + 4'd1;
    logic [WZ-1:0] atan1;
    always_comb begin
        case (sh1)
            4'd1: atan1 = 15'h025d;  // atan(2^-1)
            4'd5: atan1 = 15'h0029;  // atan(2^-5)
            4'd9: atan1 = 15'h0003;  // atan(2^-9)
            default: atan1 = '0;
        endcase
    end
    wire pos1 = ~z_c0[14];
    wire signed [WX:0] ysh1_w = $signed({y_c0, 1'b0}) >>> sh1;
    wire signed [WX:0] xsh1_w = $signed({x_c0, 1'b0}) >>> sh1;
    wire [WX-1:0] ysh1 = ysh1_w[16:1];
    wire [WX-1:0] xsh1 = xsh1_w[16:1];
    wire signed [WX-1:0] x_c1 = x_c0 + (ysh1 ^ {16{pos1}}) + {15'b0, (pos1 ^ ysh1_w[0])};
    wire signed [WX-1:0] y_c1 = y_c0 + (xsh1 ^ {16{~pos1}}) + {15'b0, (~pos1 ^ xsh1_w[0])};
    wire signed [WZ-1:0] z_c1 = z_c0 + (atan1 ^ {15{pos1}}) + {14'b0, pos1};

    // ---- chained micro-rotation 2 of 4: shift amount base+2 ----
    wire [3:0] sh2 = base + 4'd2;
    logic [WZ-1:0] atan2;
    always_comb begin
        case (sh2)
            4'd2: atan2 = 15'h013f;  // atan(2^-2)
            4'd6: atan2 = 15'h0014;  // atan(2^-6)
            4'd10: atan2 = 15'h0001;  // atan(2^-10)
            default: atan2 = '0;
        endcase
    end
    wire pos2 = ~z_c1[14];
    wire signed [WX:0] ysh2_w = $signed({y_c1, 1'b0}) >>> sh2;
    wire signed [WX:0] xsh2_w = $signed({x_c1, 1'b0}) >>> sh2;
    wire [WX-1:0] ysh2 = ysh2_w[16:1];
    wire [WX-1:0] xsh2 = xsh2_w[16:1];
    wire signed [WX-1:0] x_c2 = x_c1 + (ysh2 ^ {16{pos2}}) + {15'b0, (pos2 ^ ysh2_w[0])};
    wire signed [WX-1:0] y_c2 = y_c1 + (xsh2 ^ {16{~pos2}}) + {15'b0, (~pos2 ^ xsh2_w[0])};
    wire signed [WZ-1:0] z_c2 = z_c1 + (atan2 ^ {15{pos2}}) + {14'b0, pos2};

    // ---- chained micro-rotation 3 of 4: shift amount base+3 ----
    wire [3:0] sh3 = base + 4'd3;
    logic [WZ-1:0] atan3;
    always_comb begin
        case (sh3)
            4'd3: atan3 = 15'h00a2;  // atan(2^-3)
            4'd7: atan3 = 15'h000a;  // atan(2^-7)
            default: atan3 = '0;
        endcase
    end
    wire pos3 = ~z_c2[14];
    wire signed [WX:0] ysh3_w = $signed({y_c2, 1'b0}) >>> sh3;
    wire signed [WX:0] xsh3_w = $signed({x_c2, 1'b0}) >>> sh3;
    wire [WX-1:0] ysh3 = ysh3_w[16:1];
    wire [WX-1:0] xsh3 = xsh3_w[16:1];
    wire act3 = (sh3 < 4'd11);
    wire signed [WX-1:0] x_c3 = act3 ? (x_c2 + (ysh3 ^ {16{pos3}}) + {15'b0, (pos3 ^ ysh3_w[0])}) : x_c2;
    wire signed [WX-1:0] y_c3 = act3 ? (y_c2 + (xsh3 ^ {16{~pos3}}) + {15'b0, (~pos3 ^ xsh3_w[0])}) : y_c2;
    wire signed [WZ-1:0] z_c3 = act3 ? (z_c2 + (atan3 ^ {15{pos3}}) + {14'b0, pos3}) : z_c2;

    always_ff @(posedge clk) begin
        if (rst) begin
            state     <= S_IDLE;
            valid_out <= 1'b0;
        end else begin
            valid_out <= 1'b0;
            case (state)
                S_IDLE: if (valid_in) begin
                    quadrant <= theta_in[11:10];
                    x        <= INIT_X;
                    y        <= '0;
                    z        <= {{2{theta_in[11]}}, theta_in, 1'b0};
                    base     <= '0;
                    state    <= S_PRE;
                end
                S_PRE: begin  // rotate (pi/2, pi) by -pi and (-pi, -pi/2) by +pi
                    if (quadrant == 2'b01) begin x <= -x; z <= z - PI; end
                    if (quadrant == 2'b10) begin x <= -x; z <= z + PI; end
                    state <= S_ITER;
                end
                S_ITER: begin
                    x <= x_c3;
                    y <= y_c3;
                    z <= z_c3;
                    if (base == 4'd8) state <= S_OUT;
                    else base <= base + 4'd4;
                end
                default: begin  // S_OUT: drop guard bits, present the result
                    cos_out   <= x[13:2] + {11'b0, x[1]};
                    sin_out   <= y[13:2] + {11'b0, y[1]};
                    valid_out <= 1'b1;
                    state     <= S_IDLE;
                end
            endcase
        end
    end
endmodule
`default_nettype wire
