// Generated by hw_dse.rtl.generator -- do not edit; regenerate instead.
// family pipelined_m: a pipeline register every 3 micro-rotations
// design key: pipelined_m:data_width=12,n_iter=13,angle_guard=-1,frac_guard=1,rounding=round,m=3
// latency 7 cycles (valid_in sampled -> valid_out), one result every 1 cycle(s)
// atan LUT (hw_dse.models.cordic_bitexact.atan_lut(N=13, A=11)): [256, 151, 80, 41, 20, 10, 5, 3, 1, 1, 0, 0, 0]
// gain pre-compensation (init_x(N=13, frac_bits=11)): 1244
`default_nettype none
module cordic_golden_pipelined_m (
    input  wire                  clk,
    input  wire                  rst,
    input  wire                  valid_in,
    output wire                  ready,
    /* verilator lint_off UNUSEDSIGNAL */  // A < W: the low W-A angle bits are dropped
    input  wire signed [11:0]   theta_in,
    /* verilator lint_on UNUSEDSIGNAL */
    output logic                 valid_out,
    output logic signed [11:0]  cos_out,
    output logic signed [11:0]  sin_out
);
    /* verilator lint_off UNUSEDPARAM */  // documentation: the knobs this module was built for
    localparam int W  = 12;   // data width: angle in, sin/cos out (Q1.10)
    localparam int N  = 13;   // micro-rotations
    localparam int A  = 11;   // angle path width (angle_guard -1)
    localparam int G  = 1;   // fractional guard bits on x/y
    localparam int WX = 15;   // x/y register width = W + 2 headroom + G
    localparam int WZ = 13;   // z register width = A + 2 headroom
    localparam bit ROUND = 1'b1;  // round
    localparam int LATENCY = 7;
    /* verilator lint_on UNUSEDPARAM */
    localparam logic [WX-1:0] INIT_X = 15'h04dc;  // K_N in Q1.11
    localparam logic [WZ-1:0] PI     = 13'h0400;  // pi in angle units

    assign ready = 1'b1;  // fully pipelined: a new angle every cycle

    // ---- stage 0: register the input with the quadrant pre-rotation ----
    // Angles in (pi/2, pi) or (-pi, -pi/2) are rotated by -/+pi into the
    // CORDIC convergence range; that flips the sign of x0 (y0 is 0).
    wire [1:0] quadrant = theta_in[11:10];
    wire signed [WZ-1:0] z_in = {{2{theta_in[11]}}, theta_in[11:1]};
    logic signed [WX-1:0] x_s0;
    logic signed [WZ-1:0] z_s0;
    always_ff @(posedge clk) begin
        case (quadrant)
            2'b01:   begin x_s0 <= -INIT_X; z_s0 <= z_in - PI; end  // (pi/2, pi)
            2'b10:   begin x_s0 <= -INIT_X; z_s0 <= z_in + PI; end  // (-pi, -pi/2)
            default: begin x_s0 <=  INIT_X; z_s0 <= z_in;      end
        endcase
    end

    // valid chain: 7 registers (stage 0, 5 rotation stage(s), output)
    logic [6:0] valid_pipe;
    always_ff @(posedge clk) begin
        if (rst) valid_pipe <= '0;
        else     valid_pipe <= {valid_pipe[5:0], valid_in};
    end
    assign valid_out = valid_pipe[6];

    // ---- stage 1: micro-rotation(s) 0..2, then a register ----
    // micro-rotation 0: shift 0, atan(2^-0) = 256 (angle LSBs)
    wire x_r0_pos = ~z_s0[12];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r0 = x_s0;
    wire signed [WX-1:0] y_r0 = x_r0_pos ? x_s0 : -x_s0;
    wire signed [WZ-1:0] z_r0 = z_s0 + (13'h0100 ^ {13{x_r0_pos}}) + {12'b0, x_r0_pos};
    // micro-rotation 1: shift 1, atan(2^-1) = 151 (angle LSBs)
    wire x_r1_pos = ~z_r0[12];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r1 = x_r0 + ({{1{y_r0[14]}}, y_r0[14:1]} ^ {15{x_r1_pos}}) + {14'b0, (x_r1_pos ^ y_r0[0])};
    wire signed [WX-1:0] y_r1 = y_r0 + ({{1{x_r0[14]}}, x_r0[14:1]} ^ {15{~x_r1_pos}}) + {14'b0, (~x_r1_pos ^ x_r0[0])};
    wire signed [WZ-1:0] z_r1 = z_r0 + (13'h0097 ^ {13{x_r1_pos}}) + {12'b0, x_r1_pos};
    // micro-rotation 2: shift 2, atan(2^-2) = 80 (angle LSBs)
    wire x_r2_pos = ~z_r1[12];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r2 = x_r1 + ({{2{y_r1[14]}}, y_r1[14:2]} ^ {15{x_r2_pos}}) + {14'b0, (x_r2_pos ^ y_r1[1])};
    wire signed [WX-1:0] y_r2 = y_r1 + ({{2{x_r1[14]}}, x_r1[14:2]} ^ {15{~x_r2_pos}}) + {14'b0, (~x_r2_pos ^ x_r1[1])};
    wire signed [WZ-1:0] z_r2 = z_r1 + (13'h0050 ^ {13{x_r2_pos}}) + {12'b0, x_r2_pos};
    logic signed [WX-1:0] x_s1, y_s1;
    logic signed [WZ-1:0] z_s1;
    always_ff @(posedge clk) begin
        x_s1 <= x_r2;
        y_s1 <= y_r2;
        z_s1 <= z_r2;
    end

    // ---- stage 2: micro-rotation(s) 3..5, then a register ----
    // micro-rotation 3: shift 3, atan(2^-3) = 41 (angle LSBs)
    wire x_r3_pos = ~z_s1[12];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r3 = x_s1 + ({{3{y_s1[14]}}, y_s1[14:3]} ^ {15{x_r3_pos}}) + {14'b0, (x_r3_pos ^ y_s1[2])};
    wire signed [WX-1:0] y_r3 = y_s1 + ({{3{x_s1[14]}}, x_s1[14:3]} ^ {15{~x_r3_pos}}) + {14'b0, (~x_r3_pos ^ x_s1[2])};
    wire signed [WZ-1:0] z_r3 = z_s1 + (13'h0029 ^ {13{x_r3_pos}}) + {12'b0, x_r3_pos};
    // micro-rotation 4: shift 4, atan(2^-4) = 20 (angle LSBs)
    wire x_r4_pos = ~z_r3[12];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r4 = x_r3 + ({{4{y_r3[14]}}, y_r3[14:4]} ^ {15{x_r4_pos}}) + {14'b0, (x_r4_pos ^ y_r3[3])};
    wire signed [WX-1:0] y_r4 = y_r3 + ({{4{x_r3[14]}}, x_r3[14:4]} ^ {15{~x_r4_pos}}) + {14'b0, (~x_r4_pos ^ x_r3[3])};
    wire signed [WZ-1:0] z_r4 = z_r3 + (13'h0014 ^ {13{x_r4_pos}}) + {12'b0, x_r4_pos};
    // micro-rotation 5: shift 5, atan(2^-5) = 10 (angle LSBs)
    wire x_r5_pos = ~z_r4[12];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r5 = x_r4 + ({{5{y_r4[14]}}, y_r4[14:5]} ^ {15{x_r5_pos}}) + {14'b0, (x_r5_pos ^ y_r4[4])};
    wire signed [WX-1:0] y_r5 = y_r4 + ({{5{x_r4[14]}}, x_r4[14:5]} ^ {15{~x_r5_pos}}) + {14'b0, (~x_r5_pos ^ x_r4[4])};
    wire signed [WZ-1:0] z_r5 = z_r4 + (13'h000a ^ {13{x_r5_pos}}) + {12'b0, x_r5_pos};
    logic signed [WX-1:0] x_s2, y_s2;
    logic signed [WZ-1:0] z_s2;
    always_ff @(posedge clk) begin
        x_s2 <= x_r5;
        y_s2 <= y_r5;
        z_s2 <= z_r5;
    end

    // ---- stage 3: micro-rotation(s) 6..8, then a register ----
    // micro-rotation 6: shift 6, atan(2^-6) = 5 (angle LSBs)
    wire x_r6_pos = ~z_s2[12];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r6 = x_s2 + ({{6{y_s2[14]}}, y_s2[14:6]} ^ {15{x_r6_pos}}) + {14'b0, (x_r6_pos ^ y_s2[5])};
    wire signed [WX-1:0] y_r6 = y_s2 + ({{6{x_s2[14]}}, x_s2[14:6]} ^ {15{~x_r6_pos}}) + {14'b0, (~x_r6_pos ^ x_s2[5])};
    wire signed [WZ-1:0] z_r6 = z_s2 + (13'h0005 ^ {13{x_r6_pos}}) + {12'b0, x_r6_pos};
    // micro-rotation 7: shift 7, atan(2^-7) = 3 (angle LSBs)
    wire x_r7_pos = ~z_r6[12];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r7 = x_r6 + ({{7{y_r6[14]}}, y_r6[14:7]} ^ {15{x_r7_pos}}) + {14'b0, (x_r7_pos ^ y_r6[6])};
    wire signed [WX-1:0] y_r7 = y_r6 + ({{7{x_r6[14]}}, x_r6[14:7]} ^ {15{~x_r7_pos}}) + {14'b0, (~x_r7_pos ^ x_r6[6])};
    wire signed [WZ-1:0] z_r7 = z_r6 + (13'h0003 ^ {13{x_r7_pos}}) + {12'b0, x_r7_pos};
    // micro-rotation 8: shift 8, atan(2^-8) = 1 (angle LSBs)
    wire x_r8_pos = ~z_r7[12];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r8 = x_r7 + ({{8{y_r7[14]}}, y_r7[14:8]} ^ {15{x_r8_pos}}) + {14'b0, (x_r8_pos ^ y_r7[7])};
    wire signed [WX-1:0] y_r8 = y_r7 + ({{8{x_r7[14]}}, x_r7[14:8]} ^ {15{~x_r8_pos}}) + {14'b0, (~x_r8_pos ^ x_r7[7])};
    wire signed [WZ-1:0] z_r8 = z_r7 + (13'h0001 ^ {13{x_r8_pos}}) + {12'b0, x_r8_pos};
    logic signed [WX-1:0] x_s3, y_s3;
    logic signed [WZ-1:0] z_s3;
    always_ff @(posedge clk) begin
        x_s3 <= x_r8;
        y_s3 <= y_r8;
        z_s3 <= z_r8;
    end

    // ---- stage 4: micro-rotation(s) 9..11, then a register ----
    // micro-rotation 9: shift 9, atan(2^-9) = 1 (angle LSBs)
    wire x_r9_pos = ~z_s3[12];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r9 = x_s3 + ({{9{y_s3[14]}}, y_s3[14:9]} ^ {15{x_r9_pos}}) + {14'b0, (x_r9_pos ^ y_s3[8])};
    wire signed [WX-1:0] y_r9 = y_s3 + ({{9{x_s3[14]}}, x_s3[14:9]} ^ {15{~x_r9_pos}}) + {14'b0, (~x_r9_pos ^ x_s3[8])};
    wire signed [WZ-1:0] z_r9 = z_s3 + (13'h0001 ^ {13{x_r9_pos}}) + {12'b0, x_r9_pos};
    // micro-rotation 10: shift 10, atan(2^-10) = 0 (angle LSBs)
    wire x_r10_pos = ~z_r9[12];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r10 = x_r9 + ({{10{y_r9[14]}}, y_r9[14:10]} ^ {15{x_r10_pos}}) + {14'b0, (x_r10_pos ^ y_r9[9])};
    wire signed [WX-1:0] y_r10 = y_r9 + ({{10{x_r9[14]}}, x_r9[14:10]} ^ {15{~x_r10_pos}}) + {14'b0, (~x_r10_pos ^ x_r9[9])};
    wire signed [WZ-1:0] z_r10 = z_r9 + (13'h0000 ^ {13{x_r10_pos}}) + {12'b0, x_r10_pos};
    // micro-rotation 11: shift 11, atan(2^-11) = 0 (angle LSBs)
    wire x_r11_pos = ~z_r10[12];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r11 = x_r10 + ({{11{y_r10[14]}}, y_r10[14:11]} ^ {15{x_r11_pos}}) + {14'b0, (x_r11_pos ^ y_r10[10])};
    wire signed [WX-1:0] y_r11 = y_r10 + ({{11{x_r10[14]}}, x_r10[14:11]} ^ {15{~x_r11_pos}}) + {14'b0, (~x_r11_pos ^ x_r10[10])};
    wire signed [WZ-1:0] z_r11 = z_r10 + (13'h0000 ^ {13{x_r11_pos}}) + {12'b0, x_r11_pos};
    logic signed [WX-1:0] x_s4, y_s4;
    /* verilator lint_off UNUSEDSIGNAL */ logic signed [WZ-1:0] z_s4; /* verilator lint_on UNUSEDSIGNAL */
    always_ff @(posedge clk) begin
        x_s4 <= x_r11;
        y_s4 <= y_r11;
        z_s4 <= z_r11;
    end

    // ---- stage 5: micro-rotation(s) 12..12, then a register ----
    // micro-rotation 12: shift 12, atan(2^-12) = 0 (angle LSBs)
    wire x_r12_pos = ~z_s4[12];  // residual angle z >= 0: rotate clockwise
    wire signed [WX-1:0] x_r12 = x_s4 + ({{12{y_s4[14]}}, y_s4[14:12]} ^ {15{x_r12_pos}}) + {14'b0, (x_r12_pos ^ y_s4[11])};
    wire signed [WX-1:0] y_r12 = y_s4 + ({{12{x_s4[14]}}, x_s4[14:12]} ^ {15{~x_r12_pos}}) + {14'b0, (~x_r12_pos ^ x_s4[11])};
    /* verilator lint_off UNUSEDSIGNAL */
    logic signed [WX-1:0] x_s5, y_s5;
    /* verilator lint_on UNUSEDSIGNAL */
    always_ff @(posedge clk) begin
        x_s5 <= x_r12;
        y_s5 <= y_r12;
    end

    // ---- output register: drop the guard bits ----
    always_ff @(posedge clk) begin
        cos_out <= x_s5[12:1] + {11'b0, x_s5[0]};
        sin_out <= y_s5[12:1] + {11'b0, y_s5[0]};
    end
endmodule
`default_nettype wire
