// Generated by hw_dse.rtl.generator -- do not edit; regenerate instead.
// family iterative: 1 micro-rotation per cycle (FSM, barrel shifters)
// design key: iterative:data_width=16,n_iter=14,angle_guard=0,frac_guard=0,rounding=trunc
// latency 17 cycles (valid_in sampled -> valid_out), one result every 17 cycle(s)
// atan LUT (hw_dse.models.cordic_bitexact.atan_lut(N=14, A=16)): [8192, 4836, 2555, 1297, 651, 326, 163, 81, 41, 20, 10, 5, 3, 1]
// gain pre-compensation (init_x(N=14, frac_bits=14)): 9949
`default_nettype none
module cordic_golden_iterative (
    input  wire                  clk,
    input  wire                  rst,
    input  wire                  valid_in,
    output wire                  ready,
    input  wire signed [15:0]   theta_in,
    output logic                 valid_out,
    output logic signed [15:0]  cos_out,
    output logic signed [15:0]  sin_out
);
    /* verilator lint_off UNUSEDPARAM */  // documentation: the knobs this module was built for
    localparam int W  = 16;   // data width: angle in, sin/cos out (Q1.14)
    localparam int N  = 14;   // micro-rotations
    localparam int A  = 16;   // angle path width (angle_guard +0)
    localparam int G  = 0;   // fractional guard bits on x/y
    localparam int WX = 18;   // x/y register width = W + 2 headroom + G
    localparam int WZ = 18;   // z register width = A + 2 headroom
    localparam bit ROUND = 1'b0;  // trunc
    localparam int LATENCY = 17;
    /* verilator lint_on UNUSEDPARAM */
    localparam logic [WX-1:0] INIT_X = 18'h026dd;  // K_N in Q1.14
    localparam logic [WZ-1:0] PI     = 18'h08000;  // pi in angle units

    // FSM: IDLE (accept) -> PRE (quadrant pre-rotation) -> ITER x 14 -> OUT
    localparam logic [1:0] S_IDLE = 2'd0, S_PRE = 2'd1, S_ITER = 2'd2, S_OUT = 2'd3;
    logic [1:0] state;
    logic [1:0] quadrant;
    logic [3:0] base;  // shift amount of the first rotation this cycle (steps of 1)
    logic signed [WX-1:0] x, y;
    logic signed [WZ-1:0] z;
    assign ready = (state == S_IDLE);

    // ---- chained micro-rotation 0 of 1: shift amount base+0 ----
    wire [3:0] sh0 = base + 4'd0;
    logic [WZ-1:0] atan0;
    always_comb begin
        case (sh0)
            4'd0: atan0 = 18'h02000;  // atan(2^-0)
            4'd1: atan0 = 18'h012e4;  // atan(2^-1)
            4'd2: atan0 = 18'h009fb;  // atan(2^-2)
            4'd3: atan0 = 18'h00511;  // atan(2^-3)
            4'd4: atan0 = 18'h0028b;  // atan(2^-4)
            4'd5: atan0 = 18'h00146;  // atan(2^-5)
            4'd6: atan0 = 18'h000a3;  // atan(2^-6)
            4'd7: atan0 = 18'h00051;  // atan(2^-7)
            4'd8: atan0 = 18'h00029;  // atan(2^-8)
            4'd9: atan0 = 18'h00014;  // atan(2^-9)
            4'd10: atan0 = 18'h0000a;  // atan(2^-10)
            4'd11: atan0 = 18'h00005;  // atan(2^-11)
            4'd12: atan0 = 18'h00003;  // atan(2^-12)
            4'd13: atan0 = 18'h00001;  // atan(2^-13)
            default: atan0 = '0;
        endcase
    end
    wire pos0 = ~z[17];
    wire [WX-1:0] ysh0 = y >>> sh0;
    wire [WX-1:0] xsh0 = x >>> sh0;
    wire signed [WX-1:0] x_c0 = x + (ysh0 ^ {18{pos0}}) + {17'b0, pos0};
    wire signed [WX-1:0] y_c0 = y + (xsh0 ^ {18{~pos0}}) + {17'b0, ~pos0};
    wire signed [WZ-1:0] z_c0 = z + (atan0 ^ {18{pos0}}) + {17'b0, pos0};

    always_ff @(posedge clk) begin
        if (rst) begin
            state     <= S_IDLE;
            valid_out <= 1'b0;
        end else begin
            valid_out <= 1'b0;
            case (state)
                S_IDLE: if (valid_in) begin
                    quadrant <= theta_in[15:14];
                    x        <= INIT_X;
                    y        <= '0;
                    z        <= {{2{theta_in[15]}}, theta_in};
                    base     <= '0;
                    state    <= S_PRE;
                end
                S_PRE: begin  // rotate (pi/2, pi) by -pi and (-pi, -pi/2) by +pi
                    if (quadrant == 2'b01) begin x <= -x; z <= z - PI; end
                    if (quadrant == 2'b10) begin x <= -x; z <= z + PI; end
                    state <= S_ITER;
                end
                S_ITER: begin
                    x <= x_c0;
                    y <= y_c0;
                    z <= z_c0;
                    if (base == 4'd13) state <= S_OUT;
                    else base <= base + 4'd1;
                end
                default: begin  // S_OUT: drop guard bits, present the result
                    cos_out   <= x[15:0];
                    sin_out   <= y[15:0];
                    valid_out <= 1'b1;
                    state     <= S_IDLE;
                end
            endcase
        end
    end
endmodule
`default_nettype wire
