// equiv_m3_round: cordic_pipelined_m_m3_w8_n9_am1_g2_round (latency 5) == cordic_pipelined_w8_n9_am1_g2_round (latency 11)
// after delaying the shorter pipeline by 6 cycle(s). Generated by hw_dse.rtl.formal; do not edit.
module equiv_m3_round (
    input  wire       clk,
    input  wire       rst,
    input  wire       valid_in,
    input  wire [7:0] theta_in
);
    reg init = 1'b1;
    always @(posedge clk) init <= 1'b0;
    always @(*) if (init) assume (rst);

    wire r_ready, r_valid, m_ready, m_valid;
    wire [7:0] r_cos, r_sin, m_cos, m_sin;
    cordic_pipelined_w8_n9_am1_g2_round ref_i (.clk(clk), .rst(rst), .valid_in(valid_in), .ready(r_ready), .theta_in(theta_in),
        .valid_out(r_valid), .cos_out(r_cos), .sin_out(r_sin));
    cordic_pipelined_m_m3_w8_n9_am1_g2_round dut_i (.clk(clk), .rst(rst), .valid_in(valid_in), .ready(m_ready), .theta_in(theta_in),
        .valid_out(m_valid), .cos_out(m_cos), .sin_out(m_sin));

    // align: delay the pipelined_m outputs by 6 cycle(s)
    reg [6:0] dv;
    reg [7:0] dc [0:6];
    reg [7:0] ds [0:6];
    always @(*) begin dv[0] = m_valid; dc[0] = m_cos; ds[0] = m_sin; end
    integer i;
    always @(posedge clk) begin
        for (i = 1; i <= 6; i = i + 1) begin
            dv[i] <= rst ? 1'b0 : dv[i-1];
            dc[i] <= dc[i-1];
            ds[i] <= ds[i-1];
        end
    end

    always @(*) begin
        if (!init) begin
            assert (r_ready && m_ready);
            assert (r_valid == dv[6]);
            if (r_valid) assert (r_cos == dc[6] && r_sin == ds[6]);
        end
    end
endmodule
