// latency_pipelined: cordic_pipelined_w8_n7_ap0_g0_trunc, documented latency 9. Generated by hw_dse.rtl.formal; do not edit.
module latency_pipelined (
    input  wire       clk,
    input  wire       rst,
    input  wire       valid_in,
    input  wire [7:0] theta_in
);
    reg init = 1'b1;
    always @(posedge clk) init <= 1'b0;
    always @(*) if (init) assume (rst);

    wire ready, valid_out;
    wire [7:0] cos_out, sin_out;
    cordic_pipelined_w8_n7_ap0_g0_trunc dut_i (.clk(clk), .rst(rst), .valid_in(valid_in), .ready(ready), .theta_in(theta_in),
        .valid_out(valid_out), .cos_out(cos_out), .sin_out(sin_out));

    // acc_hist[j] = an angle was accepted j cycles ago (0 after reset)
    wire accept = valid_in && ready && !rst;
    reg [9:1] acc_hist;
    always @(posedge clk) begin
        if (rst) acc_hist <= '0;
        else     acc_hist <= {acc_hist[8:1], accept};
    end

    always @(*) begin
        if (!init && !rst) begin
            // exactly one result per accepted angle, exactly 9 cycles later
            assert (valid_out == acc_hist[9]);
            assert (ready);  // a new angle every cycle
        end
    end
endmodule
