// latency_unrolled_k: cordic_unrolled_k_k4_w8_n9_ap0_g2_round, documented latency 6. Generated by hw_dse.rtl.formal; do not edit.
module latency_unrolled_k (
    input  wire       clk,
    input  wire       rst,
    input  wire       valid_in,
    input  wire [7:0] theta_in
);
    reg init = 1'b1;
    always @(posedge clk) init <= 1'b0;
    always @(*) if (init) assume (rst);

    wire ready, valid_out;
    wire [7:0] cos_out, sin_out;
    cordic_unrolled_k_k4_w8_n9_ap0_g2_round dut_i (.clk(clk), .rst(rst), .valid_in(valid_in), .ready(ready), .theta_in(theta_in),
        .valid_out(valid_out), .cos_out(cos_out), .sin_out(sin_out));

    // acc_hist[j] = an angle was accepted j cycles ago (0 after reset)
    wire accept = valid_in && ready && !rst;
    reg [6:1] acc_hist;
    reg [6:0] since_rst;  // one-hot-ish: cycles since reset, saturating at 6
    always @(posedge clk) begin
        if (rst) begin
            acc_hist  <= '0;
            since_rst <= '0;
        end else begin
            acc_hist  <= {acc_hist[5:1], accept};
            since_rst <= (since_rst == 6) ? since_rst : since_rst + 1'b1;
        end
    end

    always @(*) begin
        if (!init && !rst) begin
            // exactly one result per accepted angle, exactly 6 cycles later
            assert (valid_out == acc_hist[6]);
            // busy for the 5 cycles after an accept, then ready again
            if (since_rst >= 6) assert (ready == !(acc_hist[1] || acc_hist[2] || acc_hist[3] || acc_hist[4] || acc_hist[5]));
        end
    end
endmodule
