// latency_pipelined_m: cordic_pipelined_m_m3_w8_n7_ap0_g0_trunc, documented latency 5. Generated by hw_dse.rtl.formal; do not edit.
module latency_pipelined_m (
    input  wire       clk,
    input  wire       rst,
    input  wire       valid_in,
    input  wire [7:0] theta_in
);
    reg init = 1'b1;
    always @(posedge clk) init <= 1'b0;
    always @(*) if (init) assume (rst);

    wire ready, valid_out;
    wire [7:0] cos_out, sin_out;
    cordic_pipelined_m_m3_w8_n7_ap0_g0_trunc dut_i (.clk(clk), .rst(rst), .valid_in(valid_in), .ready(ready), .theta_in(theta_in),
        .valid_out(valid_out), .cos_out(cos_out), .sin_out(sin_out));

    // acc_hist[j] = an angle was accepted j cycles ago (0 after reset)
    wire accept = valid_in && ready && !rst;
    reg [5:1] acc_hist;
    reg [5:0] since_rst;  // one-hot-ish: cycles since reset, saturating at 5
    always @(posedge clk) begin
        if (rst) begin
            acc_hist  <= '0;
            since_rst <= '0;
        end else begin
            acc_hist  <= {acc_hist[4:1], accept};
            since_rst <= (since_rst == 5) ? since_rst : since_rst + 1'b1;
        end
    end

    always @(*) begin
        if (!init && !rst) begin
            // exactly one result per accepted angle, exactly 5 cycles later
            assert (valid_out == acc_hist[5]);
            assert (ready);  // a new angle every cycle
        end
    end
endmodule
