#!/usr/bin/env python3
"""Prepare and collect the Vivado measurements for the L5 refit (run Vivado elsewhere).

Step 1, here:  export the recommended points as generated RTL plus a Vivado TCL
script per design that repeats the anchors' flow exactly (in-memory project,
xc7a35tcpg236-1, 10 ns clock, ``synth_design``, utilisation + timing reports):

    python scripts/vivado_points.py export --out vivado_points/

Step 2, on a machine with Vivado 2025.2:

    cd vivado_points && ./run_all.sh          # vivado -mode batch -source <design>/run.tcl, per design

Step 3, here again: parse the reports into a measured-points CSV (the schema of
``hw_dse.synth.measured``) and refit:

    python scripts/vivado_points.py collect --dir vivado_points/ --out eval/data/vivado_measured.csv
    python -m hw_dse.synth.recalibrate --measured eval/data/vivado_measured.csv \\
        --measured eval/data/vivado_measured_2.csv --measured eval/data/l4_synthesis.csv \\
        --measured eval/data/vivado_spotcheck.csv --name vivado-2025.2

(The committed ``eval/data/vivado_measured.csv`` / ``vivado_measured_2.csv`` were
collected from the reports copied into ``eval/data/vivado_logs/`` / ``vivado_logs_2/``;
batch 2 set ``POINTS`` to other designs before calling :func:`export`. See
``eval/data/README.md``.)

Fmax is computed as the anchors' was, ``1000 / (10 - WNS)`` from the
post-synthesis timing summary. Add ``--route`` to ``export`` to also place and
route (``opt_design; place_design; route_design``) and report post-route
timing; those rows are written with ``fmax_kind`` saying so, and the refit
reports them without fitting them.

The points (``POINTS``): the six from ``hw_dse.synth.sweep.VIVADO_POINTS``
(``unrolled_k`` k=2/4, ``pipelined_m`` m=2/4, ``pipelined`` W=12/24) plus the
two *generated* anchors (``iterative`` and ``pipelined``, W=16, N=14), which
test the refit's assumption that Vivado gives the same numbers for generated
and reference RTL.
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from hw_dse.families import ArchConfig  # noqa: E402
from hw_dse.rtl.generator import generate  # noqa: E402
from hw_dse.synth import measured  # noqa: E402
from hw_dse.synth.sweep import ANCHORS, VIVADO_POINTS  # noqa: E402

PART = "xc7a35tcpg236-1"
PERIOD_NS = 10.0
POINTS: list[ArchConfig] = VIVADO_POINTS + ANCHORS

TCL = """# Generated by scripts/vivado_points.py: the anchors' flow (CORDIC repo synthesis_logs/), for one design.
set_param general.maxThreads 4
create_project -in_memory -part {part}
read_verilog -sv [file join [file dirname [info script]] {module}.sv]
set xdc [file join [file dirname [info script]] clock.xdc]
read_xdc $xdc
synth_design -top {module} -part {part}
report_utilization -file [file join [file dirname [info script]] utilization.rpt]
report_timing_summary -file [file join [file dirname [info script]] timing.rpt]
{route}"""
ROUTE = """opt_design
place_design
route_design
report_utilization -file [file join [file dirname [info script]] utilization_routed.rpt]
report_timing_summary -file [file join [file dirname [info script]] timing_routed.rpt]
"""


def export(out: Path, route: bool) -> None:
    out.mkdir(parents=True, exist_ok=True)
    names = []
    for a in POINTS:
        d = generate(a)
        wd = out / d.module
        d.write(wd)
        (wd / "clock.xdc").write_text(f"create_clock -period {PERIOD_NS:.3f} -name clk [get_ports clk]\n")
        (wd / "run.tcl").write_text(TCL.format(part=PART, module=d.module, route=ROUTE if route else ""))
        (wd / "design_key.txt").write_text(a.key() + "\n")
        names.append(d.module)
    (out / "run_all.sh").write_text("#!/usr/bin/env bash\nset -e\ncd \"$(dirname \"$0\")\"\n" + "".join(
        f"vivado -mode batch -nojournal -log {n}/vivado.log -source {n}/run.tcl\n" for n in names))
    (out / "run_all.sh").chmod(0o755)
    print(f"exported {len(names)} designs to {out}; run {out}/run_all.sh with Vivado, then `collect`")


def parse_utilization(text: str) -> dict[str, int]:
    """Slice LUTs, Slice Registers (the anchors' figures) and CARRY4 from report_utilization."""
    out: dict[str, int] = {}
    for label, key in (("Slice LUTs", "luts"), ("Slice Registers", "ffs")):
        m = re.search(rf"^\|\s*{label}\*?\s*\|\s*(\d+)\s*\|", text, re.M)
        if m:
            out[key] = int(m.group(1))
    m = re.search(r"^\|\s*CARRY4\s*\|\s*(\d+)\s*\|", text, re.M)
    if m:
        out["carry4"] = int(m.group(1))
    return out


def parse_wns(text: str) -> float:
    """WNS (ns) from the Design Timing Summary of report_timing_summary."""
    m = re.search(r"Design Timing Summary.*?WNS\(ns\).*?\n\s*-+.*?\n\s*(-?[0-9.]+)", text, re.S)
    if not m:
        raise ValueError("no Design Timing Summary WNS in report")
    return float(m.group(1))


def collect(directory: Path, out: Path, version: str) -> None:
    pts = []
    for wd in sorted(p for p in directory.iterdir() if (p / "design_key.txt").exists()):
        arch = ArchConfig.from_key((wd / "design_key.txt").read_text().strip())
        for suffix, kind in (("", "post-synthesis (1000/(10-WNS)), as the anchors"),
                             ("_routed", "post-route (1000/(10-WNS))")):
            u, tm = wd / f"utilization{suffix}.rpt", wd / f"timing{suffix}.rpt"
            if not (u.exists() and tm.exists()):
                continue
            util = parse_utilization(u.read_text())
            wns = parse_wns(tm.read_text())
            pts.append(measured.MeasuredPoint(
                "vivado", version, PART, "generated", arch, float(util["luts"]), float(util["ffs"]),
                round(1000.0 / (PERIOD_NS - wns), 2), float(util.get("carry4", 0)),
                {"fmax_kind": f"{kind}; WNS {wns} ns at {PERIOD_NS} ns", "target_mhz": f"{1000 / PERIOD_NS:g}",
                 "command": f"vivado -mode batch -source {wd.name}/run.tcl",
                 "source_log": f"{wd.name}/utilization{suffix}.rpt, {wd.name}/timing{suffix}.rpt"}))
    if not pts:
        raise SystemExit(f"no reports found under {directory}")
    measured.write(out, pts)
    measured.load(out)  # validate against the schema
    print(f"wrote {out} ({len(pts)} rows)")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    e = sub.add_parser("export")
    e.add_argument("--out", default="vivado_points")
    e.add_argument("--route", action="store_true", help="also place and route, report post-route timing")
    c = sub.add_parser("collect")
    c.add_argument("--dir", default="vivado_points")
    c.add_argument("--out", default=str(ROOT / "eval" / "data" / "vivado_measured.csv"))
    c.add_argument("--version", default="2025.2")
    args = ap.parse_args()
    if args.cmd == "export":
        export(Path(args.out), args.route)
    else:
        collect(Path(args.dir), Path(args.out), args.version)


if __name__ == "__main__":
    main()
