#!/usr/bin/env python3
"""The L2 rung, worked: two designs in a system.

    python scripts/worked_example_m3.py      # writes docs/worked_example_m3.md

Continues ``docs/worked_example_m2.md`` (L1 -> L3 -> gate level -> L4 -> L5 for
the ``low_area_control`` winner) with the rung milestone 3 adds:

1. the design's interface contract, from the cycle model, checked against
   its generated RTL cycle for cycle on a bursty trace (Icarus, if installed);
2. the DDS spectrum of its exact outputs;
3. the same design dropped into the ``bursty_offload`` system: L1 bound vs L2
   simulation, and why the spec's winner is a different family;
4. ``multiaxis_control``: three views (MSPS-only, L1 bound, L2 simulated), three
   different winners, and the clock-edge alignment effect that separates the
   last two.

Every number is computed here by code, with its provenance.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from hw_dse import accuracy_table  # noqa: E402
from hw_dse.evaluate import evaluate  # noqa: E402
from hw_dse.families import ArchConfig  # noqa: E402
from hw_dse.l2.cycle import Contract  # noqa: E402
from hw_dse.l2.dds import PROVENANCE as DDS_PROV  # noqa: E402
from hw_dse.l2.dds import dds_spectrum  # noqa: E402
from hw_dse.l2.node import simulate_record  # noqa: E402
from hw_dse.rtl.sim import tool_status  # noqa: E402
from hw_dse.spec import load_spec  # noqa: E402

OUT = ROOT / "docs" / "worked_example_m3.md"


def main() -> None:
    accuracy_table.preload()
    gt3 = json.loads((ROOT / "eval" / "data" / "ground_truth_m3.json").read_text())
    arch = ArchConfig.from_params("iterative", {"data_width": 15, "n_iter": 12, "angle_guard": 1, "rounding": "round"})
    L = ["# Worked example, milestone 3: the L2 rung", "",
         "Generated by `python scripts/worked_example_m3.py`; every number is computed by code and labelled with its "
         "provenance. It continues [`worked_example_m2.md`](worked_example_m2.md), which takes the same design from L1 "
         "to measured numbers.", "", f"Design: `{arch.key()}` (the exhaustive winner of `low_area_control`).", ""]

    c = Contract.of(arch)
    L += ["## 1. Interface contract (cycle model)", "",
          f"`hw_dse.l2.cycle.CycleModel`: an FSM (IDLE → PRE → {arch.steps} × ITER → OUT); latency **{c.latency} cycles**, "
          f"`ready` high only in IDLE, so a new angle every **{c.ii} cycles**. *exact* (from the schedule)."]
    ok, why = tool_status("icarus")
    if ok:
        from hw_dse.l2.validate import validate_cycles

        v = validate_cycles(arch, "icarus", n=40, seed=1)
        L += ["", f"Checked against its generated RTL on a 40-angle bursty trace ({v.n_edges} clock edges, {v.simulator_version}): "
              f"ready mismatches {v.ready_mismatches}, valid_out mismatches {v.valid_mismatches}, output-code mismatches "
              f"{v.data_mismatches}. *exact*."]
    else:
        L += ["", f"(RTL cycle check skipped here: {why}.)"]
    sfdr, snr = dds_spectrum(arch.numerics)
    L += ["", "## 2. DDS spectrum of its exact outputs", "",
          f"SFDR **{sfdr:.1f} dBc**, SNR **{snr:.1f} dB** (*{DDS_PROV}*).", ""]

    spec = load_spec(ROOT / "specs" / "system" / "bursty_offload.yaml")
    rec = evaluate(arch, spec)
    sim = simulate_record(rec, spec)
    g = gt3["bursty_offload"]
    L += ["## 3. In a bursty system (`bursty_offload`)", "",
          f"System: {spec.system.describe()}; constraint p99 latency ≤ 0.4 µs.", "",
          "| metric | L1 (bound) | L2 (simulated) |", "|---|---|---|"]
    for m in ("sys_p50_latency_us", "sys_p99_latency_us", "sys_throughput_msps"):
        L.append(f"| {m} | {rec[m]:.4g} | {sim[m]:.4g} |")
    L += ["", f"Utilisation {sim['sys_utilisation'] * 100:.1f}%, deepest queue {sim['sys_max_queue']:.0f} requests "
          f"(*{sim['provenance']['sys_p99_latency_us']}*).", "",
          f"Its throughput ({rec['throughput_msps']:.1f} MSPS, *estimate*) is 6.6x the 2 MS/s average, so the MSPS-only view "
          f"keeps it as the winner. But one request every {c.ii} cycles means the eighth request of a burst waits for seven "
          "others: even an isolated burst (the L1 bound) misses 0.4 µs, and with Poisson bursts overlapping the simulated "
          f"p99 is {sim['sys_p99_latency_us'] / rec['sys_p99_latency_us']:.1f}x the bound. Exhaustively, no FSM design meets the "
          f"constraint; the winner becomes `{g['selected']['key']}` ({g['selected']['luts_plus_ffs']:.0f} LUT+FF vs "
          f"{g['msps_only']['selected']['luts_plus_ffs']:.0f} for the MSPS-only winner), p99 "
          f"{g['selected']['sys_p99_latency_us']:.3f} µs (*simulated*).", ""]

    spec2 = load_spec(ROOT / "specs" / "system" / "multiaxis_control.yaml")
    g2 = gt3["multiaxis_control"]
    L += ["## 4. Three views, three winners (`multiaxis_control`)", "",
          f"System: {spec2.system.describe()}; all 32 results within 0.44 µs of the tick (p99 over ticks).", "",
          "| view | winner | LUT+FF | sys_p99_batch_us |", "|---|---|---|---|"]
    rows = [("MSPS-only (≥ 32 MSPS)", g2["msps_only"]["selected"]), ("L1 bound", g2["l1_bound_selected"]),
            ("L2 simulated (the truth)", g2["selected"])]
    for label, r in rows:
        a = ArchConfig.from_key(r["key"])
        e = evaluate(a, spec2)
        s = simulate_record(e, spec2)
        L.append(f"| {label} | `{r['key']}` | {e['luts_plus_ffs']:.0f} | bound {e['sys_p99_batch_us']:.4g} / simulated "
                 f"{s['sys_p99_batch_us']:.4g} |")
    mo = ArchConfig.from_key(g2["msps_only"]["selected"]["key"])
    mo_rec = evaluate(mo, spec2)
    r_ = int(spec2.system.requests_per_tick)
    need = ((r_ - 1) + (mo.latency_cycles - 1)) / 0.44
    L += ["", f"The MSPS-only winner meets the 32 requests/µs average, but serving a whole batch of {r_} within 0.44 µs needs "
          f"((32 - 1) + ({mo.latency_cycles} - 1)) cycles / 0.44 µs = {need:.1f} MHz even with perfect alignment, and its "
          f"estimated Fmax is {mo_rec['fmax_mhz']:.1f} MHz. The L1 bound (each tick served alone, starting on a clock edge) admits m=5; the "
          "simulation adds the clock-domain crossing: a tick lands between CORDIC clock edges, so up to one cycle is lost "
          "before the first accept, which pushes m=5 just past the deadline and makes m=4 the winner. The L2 node in the "
          "graph makes exactly this switch when the L1 selection is m=5.", ""]
    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
