#!/usr/bin/env python3
"""One design up the fidelity ladder: L1 estimate -> RTL -> verified -> synthesised -> measured vs estimate.

    python scripts/worked_example.py      # writes docs/worked_example_m2.md

The design is the exhaustive ground truth's winner for ``low_area_control``
(``iterative`` W=15, N=12, angle_guard=1, round). Every number printed is
computed here, by code, with its provenance:

* L1: the cost model (*estimate*, M1 calibration) and the golden model (*exact*);
* L3: the generated RTL simulated in Verilator and Icarus on all 32,768 angles
  (*exact*);
* gate level: the Yosys-mapped netlist simulated in Verilator (*exact*);
* L4: the committed measurement (*measured*, Yosys + nextpnr-xilinx), the same
  numbers ``scripts/run_l4_sweep.py`` produced;
* L5: the agent's back-annotation hook on this design, and the refit
  calibration's prediction for it.

Needs Verilator, Icarus and Yosys (docker image or native); see the README.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from hw_dse import accuracy_table  # noqa: E402
from hw_dse.agent.backannotate import DEFAULT_REFIT, back_annotate  # noqa: E402
from hw_dse.evaluate import evaluate  # noqa: E402
from hw_dse.families import ArchConfig  # noqa: E402
from hw_dse.models.cost_fpga import FpgaCostModel, load_calibration  # noqa: E402
from hw_dse.rtl.generator import generate  # noqa: E402
from hw_dse.rtl.sim import verify_rtl  # noqa: E402
from hw_dse.spec import load_spec  # noqa: E402
from hw_dse.synth import measured  # noqa: E402
from hw_dse.synth.gatesim import verify_gate  # noqa: E402
from hw_dse.synth.sweep import L4_CSV  # noqa: E402

OUT = ROOT / "docs" / "worked_example_m2.md"


def main() -> None:
    accuracy_table.preload()
    spec = load_spec(ROOT / "specs" / "low_area_control.yaml")
    arch = ArchConfig.from_params("iterative", {"data_width": 15, "n_iter": 12, "angle_guard": 1, "frac_guard": 0,
                                                "rounding": "round"})
    gt = json.loads((ROOT / "eval" / "data" / "ground_truth.json").read_text())[spec.name]
    assert gt["selected"]["key"] == arch.key()
    rec = evaluate(arch, spec)
    L = ["# Worked example: one design from L1 to measured silicon numbers", "",
         "Generated by `python scripts/worked_example.py`; every number below is computed by code and labelled with "
         "its provenance. The design is the exhaustive ground truth's winner for `low_area_control` "
         "(≥ 1 MSPS, max error ≤ 2⁻¹⁰, minimise LUTs+FFs).", "",
         f"Design: `{arch.key()}`", ""]

    # ---- L1 ---------------------------------------------------------------
    L += ["## L1: analytical estimate and exact accuracy", "",
          "| metric | value | provenance |", "|---|---|---|"]
    for m in ("luts", "ffs", "fmax_mhz", "throughput_msps", "latency_cycles", "max_abs_err", "accuracy_bits"):
        v = rec[m]
        L.append(f"| {m} | {v:.4g} | {rec['provenance'][m]} |")
    L.append("")

    # ---- L3 ---------------------------------------------------------------
    d = generate(arch)
    L += ["## L3: generated RTL, verified against the golden model", "",
          f"`hw_dse.rtl.generator` emits `{d.module}` ({len(d.text.splitlines())} lines). Its header:", "", "```systemverilog"]
    L += d.text.splitlines()[:30]
    L += ["...", "```", "",
          "| simulator | angles | mismatching outputs | latency (cycles, measured / documented) | provenance |",
          "|---|---|---|---|---|"]
    for sim in ("verilator", "icarus"):
        v = verify_rtl(arch, sim)
        L.append(f"| {v.simulator_version} | {v.sweep} | {v.mismatches} | {v.latency_measured} / {v.latency_expected} | exact |")
    L.append("")

    # ---- gate level ---------------------------------------------------------
    g = verify_gate(arch, "verilator")
    L += ["## Gate level: the synthesised netlist, simulated", "",
          f"Netlist: {g.netlist}.", "",
          f"Verilator on {g.sweep}: **{g.mismatches} mismatches**, latency {g.latency_measured} "
          f"(documented {g.latency_expected}). Provenance: exact.", ""]

    # ---- L4 ---------------------------------------------------------------
    pts = [p for p in measured.load(L4_CSV) if p.arch.key() == arch.key() and p.rtl_source == "generated"]
    p = pts[0]
    L += ["## L4: synthesised, placed and routed on xc7a35tcpg236-1", "",
          f"Provenance: {p.provenance}; Fmax: {p.extra['fmax_kind']}. Command and log: `eval/data/l4_synthesis.csv`, "
          f"`{p.extra['source_log']}`.", "",
          "| metric | L1 estimate (M1 calibration) | measured | estimate error |", "|---|---|---|---|"]
    for m, meas in (("luts", p.luts), ("ffs", p.ffs), ("fmax_mhz", p.fmax_mhz)):
        L.append(f"| {m} | {rec[m]:.1f} | {meas:.1f} | {(rec[m] / meas - 1) * 100:+.1f}% |")
    L.append("")

    # ---- L5 ---------------------------------------------------------------
    cal = load_calibration(str(DEFAULT_REFIT))
    tau = cal["tool_corrections"][p.tool]
    e = FpgaCostModel(str(DEFAULT_REFIT)).estimate(arch)
    L += ["## L5: back-annotation", "",
          f"Refit calibration `{cal['id']}` (`{DEFAULT_REFIT.relative_to(ROOT)}`, not the default): it predicts this design "
          f"on the Vivado scale, and × the fitted `{p.tool}` factors on that tool's scale:", "",
          "| metric | refit (Vivado scale) | refit × tool factor | measured | error |", "|---|---|---|---|---|"]
    for m, val, f, meas in (("luts", e.area["luts"], tau["luts"], p.luts), ("ffs", e.area["ffs"], tau["ffs"], p.ffs),
                            ("fmax_mhz", e.fmax_mhz, 1 / tau["path"], p.fmax_mhz)):
        L.append(f"| {m} | {val:.1f} | {val * f:.1f} | {meas:.1f} | {(val * f / meas - 1) * 100:+.1f}% |")
    front = [evaluate(ArchConfig.from_key(r["key"]), spec) for r in gt["front"]]
    ba = back_annotate(spec, front, rec)
    L += ["", "The agent's `back_annotate` node, run on the true front with this design selected:", "",
          f"- status: `{ba['status']}`; {ba['n_front_designs_measured']} of {ba['n_front_designs']} front designs have "
          "measurements;",
          f"- winner changed: **{ba['winner_changed']}** ({ba['why']}).", ""]
    for c in ba["comparisons"]:
        L.append(f"- {c['provenance']}: LUTs {c['luts']['estimate']:.0f} → {c['luts']['measured']:.0f} "
                 f"({c['luts']['diff_pct']:+.1f}%), FFs {c['ffs']['estimate']:.0f} → {c['ffs']['measured']:.0f} "
                 f"({c['ffs']['diff_pct']:+.1f}%), Fmax {c['fmax_mhz']['estimate']:.0f} → {c['fmax_mhz']['measured']:.0f} MHz "
                 f"({c['fmax_mhz']['diff_pct']:+.1f}%).")
    L.append("")
    L.append(f"Throughput check with the measured clock: {p.fmax_mhz:.1f} MHz / {arch.latency_cycles} cycles per result = "
             f"{p.fmax_mhz / arch.latency_cycles:.1f} MSPS against the spec's ≥ 1 MSPS: still feasible.")
    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
